import { defaultSchema, type Options as SanitizeOptions } from 'rehype-sanitize';

/** 允许作者富文本产生的有限 HTML（颜色/对齐/视频等） */
export const authorHtmlSanitizeSchema: SanitizeOptions = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    'video',
    'iframe',
    'mark',
    'span',
    'u',
    'table',
    'thead',
    'tbody',
    'tr',
    'th',
    'td',
    'colgroup',
    'col',
    'figure',
    'figcaption',
  ],
  attributes: {
    ...defaultSchema.attributes,
    '*': [...(defaultSchema.attributes?.['*'] ?? []), 'className', 'class', 'style'],
    a: [...(defaultSchema.attributes?.a ?? []), 'href', 'name', 'target', 'rel'],
    img: [...(defaultSchema.attributes?.img ?? []), 'src', 'alt', 'title', 'width', 'height'],
    video: ['src', 'controls', 'width', 'height', 'style'],
    iframe: ['src', 'width', 'height', 'allow', 'allowfullscreen', 'frameborder', 'style', 'class'],
    mark: ['style', 'dataColor', 'data-color', 'class'],
    span: [
      'style',
      'class',
      'data-line',
      'data-line-numbers',
      'data-highlighted-line',
      'data-highlighted-chars',
    ],
    code: [
      ...(defaultSchema.attributes?.code ?? []),
      'class',
      'style',
      'data-language',
      'data-theme',
      'data-line',
    ],
    pre: [
      ...(defaultSchema.attributes?.pre ?? []),
      'class',
      'style',
      'data-language',
      'data-theme',
      'tabindex',
    ],
    figure: ['class', 'data-rehype-pretty-code-figure'],
    figcaption: ['class', 'data-rehype-pretty-code-title', 'data-language'],
    p: [...(defaultSchema.attributes?.p ?? []), 'style', 'class'],
    h1: ['id', 'style', 'class'],
    h2: ['id', 'style', 'class'],
    h3: ['id', 'style', 'class'],
    td: ['colspan', 'rowspan', 'style', 'class', 'data-row-height'],
    th: ['colspan', 'rowspan', 'style', 'class', 'data-row-height'],
    tr: ['style', 'class', 'data-row-height'],
    col: ['span', 'width', 'style'],
  },
};
